---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%.
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Dave Gandy
  homepage: http://fortawesome.github.com/Font-Awesome/
  email: dave@davegandy.com
  twitter: https://twitter.com/fontawesome/
  github: https://github.com/FortAwesome/Font-Awesome
  license: SIL
  #license_url: http://creativecommons.org/licenses/by/3.0/

  css_prefix_text: "icon-"
  columns: 4

#transform:
#  baseline: 0.5
#  rescale: 1.053
#  # offset: -0.05


font:
  version: "5.2.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: fa5regular

  fullname: Font Awesome 5 Free - regular
  familyname: Font Awesome 5 Free

  copyright: Copyright (C) 2017 by Dave Gandy

  ascent: 850
  descent: 150
  weight: "Regular"


glyphs:

  - css: mail-alt
    code: 0xf0e0
    uid: ccc2329632396dc096bb638d4b46fb98
    search: [mail, email]

  - css: heart
    code: 0x2665
    uid: d73eceadda1f594cec0536087539afbf
    from: 0xf004
    search: [heart]

  - css: star
    code: 0x2605
    uid: 474656633f79ea2f1dad59ff63f6bf07
    from: 0xf005
    search: [star]

  - css: star-half
    code: 0xe701
    uid: 8f8278fbe5a2a0ea836be3c408b005d2
    from: 0xf089
    search: [star]

  - css: user
    code: 0x1f464
    uid: 8b80d36d4ef43889db10bc1f0dc9a862
    from: 0xf007
    search: [profile, contact, user]

  - css: picture
    code: 0x1f304
    uid: 381da2c2f7fd51f8de877c044d7f439d
    from: 0xf03e
    search: [image, picture, photo]

  - css: ok-circled
    code: 0x2714
    uid: 43ab845088317bd348dee1d975700c48
    from: 0xf058
    search: [ok, yes, check, mark]

  - css: ok-squared
    code: 0xf14a
    uid: 1400d5103edd2fa6d2d61688fee79a5a
    search: [ok, check]

  - css: cancel-circled
    code: 0x2716
    uid: 0f4cae16f34ae243a6144c18a003f2d8
    from: 0xf057
    search: [close, cancel, reject, times-circle]

  - css: plus-squared
    code: 0xf0fe
    uid: 1a5cfa186647e8c929c2b17b9fc4dac1
    search: [plus, plus-square]

  - css: minus-squared
    code: 0xf146
    uid: f755a58fb985eeb70bd47d9b31892a34
    search: [minus]

  - css: help-circled
    code: 0xe704
    uid: 17ebadd1e3f274ff0205601eef7b9cc4
    from: 0xf059
    search: [help, question, question-circle]

  - css: eye
    code: 0xe70a
    uid: c5fd349cbd3d23e4ade333789c29c729
    from: 0xf06e
    search: [eye, subscribe]

  - css: eye-off
    code: 0xe70b
    uid: 7fd683b2c518ceb9e5fa6757f2276faa
    from: 0xf070
    search: [eye, unsubscribe]

  - css: bookmark
    code: 0x1f516
    uid: f04a5d24e9e659145b966739c4fde82a
    from: 0xf02e
    search: [bookmark]

  - css: flag
    code: 0x2691
    uid: 57a0ac800df728aad61a7cf9e12f5fef
    from: 0xf024
    search: [flag]

  - css: thumbs-up-alt
    code: 0xf164
    uid: 5e2ab018e3044337bcef5f7e94098ea1
    search: [thumbs, vote, up, like, love]

  - css: thumbs-down-alt
    code: 0xf165
    uid: ddcd918b502642705838815d40aea9e3
    search: [thumbs, vote, down, dislike, unlike]

  - css: export-alt
    code: 0xf14d
    uid: 13b9eebfea581ad8e756ee7a18a7cba8
    search: [export, share]

  - css: edit
    code: 0x270d
    uid: 41087bc74d4b20b55059c60a33bf4008
    from: 0xf044
    search: [pencil, write, reply, edit]

  - css: keyboard
    code: 0xf11c
    uid: ecb97add13804c190456025e43ec003b
    search: [keyboard, keyboard-o]

  - css: comment
    code: 0xe718
    uid: 85528017f1e6053b2253785c31047f44
    from: 0xf075
    search: [comment, reply, write]

  - css: chat
    code: 0xe720
    uid: dcedf50ab1ede3283d7a6c70e2fe32f3
    from: 0xf086
    search: [chat, talk]

  - css: bell-alt
    code: 0xf0f3
    uid: 671f29fa10dda08074a4c6a341bb4f39
    search: [alert, bell, jingle]

  - css: bell-off
    code: 0xf1f6
    uid: 563683020e0bf9f22f3f055a69b5c57a
    search: [bell]

  - css: compass
    code: 0xf14e
    uid: e5d624264734620fa9f98d59e6dc941f
    search: [compass]

  - css: docs
    code: 0xf0c5
    uid: c8585e1e5b0467f28b70bce765d5840c
    search: [doc, file, article, copy]

  - css: doc-inv
    code: 0xf15b
    uid: 178053298e3e5b03551d754d4b9acd8b
    search: [doc, file, article]

  - css: doc-text-inv
    code: 0xf15c
    uid: c08a1cde48d96cba21d8c05fa7d7feb1
    search: [doc, file, article]

  - css: file-pdf
    code: 0xf1c1
    uid: 9daa1fdf0838118518a7e22715e83abc
    search: [file, pdf, file-pdf-o]

  - css: file-word
    code: 0xf1c2
    uid: 310ffd629da85142bc8669f010556f2d
    search: [file, word]

  - css: file-excel
    code: 0xf1c3
    uid: f761c3bbe16ba2d332914ecb28e7a042
    search: [file, excel]

  - css: file-powerpoint
    code: 0xf1c4
    uid: edcd4022de8d8df266ef7c42d2658ca5
    search: [file, powerpoint]

  - css: file-image
    code: 0xf1c5
    uid: 3c961c1a8d874815856fc6637dc5a13c
    search: [file, image, picture]

  - css: file-archive
    code: 0xf1c6
    uid: e80ae555c1413a4ec18b33fb348b4049
    search: [file, archive, file-zip-o]

  - css: file-audio
    code: 0xf1c7
    uid: 81db033e704eb7c586a365559d7c0f36
    search: [file, audio, sound]

  - css: file-video
    code: 0xf1c8
    uid: dd69d9aa589ea7bc0a82a3fe67039f4b
    search: [file, video, movie]

  - css: file-code
    code: 0xf1c9
    uid: 26613a2e6bc41593c54bead46f8c8ee3
    search: [file, code]

  - css: folder
    code: 0x1f4c1
    uid: f8aa663c489bcbd6e68ec8147dca841e
    from: 0xf07b
    search: [folder]

  - css: folder-open
    code: 0x1f4c2
    uid: c95735c17a10af81448c7fed98a04546
    from: 0xf07c
    search: [folder]

  - css: calendar
    code: 0x1f4c5
    uid: 531bc468eecbb8867d822f1c11f1e039
    from: 0xf073
    search: [calendar, date]

  - css: calendar-empty
    code: 0xf133
    uid: ead4c82d04d7758db0f076584893a8c1
    search: [calendar]

  - css: clock
    code: 0x1f554
    uid: 598a5f2bcf3521d1615de8e1881ccd17
    from: 0xf017
    search: [clock, time, clock-o]

  - css: lightbulb
    code: 0xf0eb
    uid: 5278ef7773e948d56c4d442c8c8c98cf
    search: [idea, lamp, light, lightbulb-o]

  - css: right-hand
    code: 0x261e
    from: 0xf0a4
    uid: aa0d9175a3919a260a4012d560e9f01e
    search: [hand, right, arrow]

  - css: left-hand
    code: 0x261c
    from: 0xf0a5
    uid: 3d99d345645f43e31e9e0fd48be37e9c
    search: [hand, left, arrow]

  - css: up-hand
    code: 0x261d
    from: 0xf0a6
    uid: 034e645aa3bad56ce68389a816547c87
    search: [hand, up, arrow]

  - css: down-hand
    code: 0x261f
    from: 0xf0a7
    uid: beb43b8df442eac4b8d35f528d5ed5af
    search: [hand, down, arrow]

  - css: expand
    code: 0xf150
    uid: 84bb9695b8662fa4783242f84c9e4682
    search: [expand]

  - css: collapse
    code: 0xf151
    uid: 7960517a504e42aea0641f15bc55fbed
    search: [collapse]

  - css: expand-right
    code: 0xf152
    uid: ed5a38704f0329e610ee1c92bec3ad3d
    search: [expand]

  - css: collapse-left
    code: 0xf191
    uid: ea2ec99fbce03864e593bbf4f302a79d
    search: [collapse]

  - css: play-circled
    code: 0xf144
    uid: 5717236f6134afe2d2a278a5c9b3927a
    search: [player, play]

  - css: sun
    code: 0xf185
    uid: aa035df0908c4665c269b7b09a5596f3
    search: [sun, sun-o]

  - css: moon
    code: 0xf186
    uid: 567e3e257f2cc8fba2c12bf691c9f2d8
    search: [moon]

  - css: paper-plane
    code: 0xf1d8
    uid: 38575a803c4da31ce20d77e1e1236bcb
    search: [flight, plane, airplane, fly]

  - css: list-alt
    code: 0xe790
    uid: c819c6225685bae2eed1b8da13e629fa
    from: 0xf022
    search: [list]

  - css: circle
    code: 0xf111
    uid: 130380e481a7defc690dfb24123a1f0c
    search: [circle]

  - css: dot-circled
    code: 0xf192
    uid: 81bb68665e8e595505272a746db07c7a
    search: [dot, radio]

  - css: chart-bar
    code: 0x1f4ca
    uid: 266d5d9adf15a61800477a5acf9a4462
    from: 0xf080
    search: [chart, bar, diagram, bar-chart]

  - css: credit-card
    code: 0x1f4b3
    from: 0xf09d
    uid: 3d8cc269fdad8a4cda55a20542a84e5c
    search: [card, plastic, credit]

  - css: floppy
    code: 0x1f4be
    from: 0xf0c7
    uid: f4445feb55521283572ee88bc304f928
    search: [floppy, save]

  - css: hdd
    code: 0xf0a0
    uid: 795efd07cd5205b589c883916a76cff0
    search: [hdd, drive, disk]

  - css: hospital
    code: 0xf0f8
    uid: c4adaacece4c6341a9ae1816f5ea500c
    search: [hospital      ]

  - css: building-filled
    code: 0xf1ad
    uid: ede2ea0a583f662b79fbb181b428c20d
    search: [building, building-o]

  - css: smile
    code: 0xf118
    uid: d862a10e1448589215be19702f98f2c1
    search: [emoticon, sniley, smile, happy, smile-o]

  - css: frown
    code: 0xf119
    uid: 06ddc67d609c477cd5524a7238d7850d
    search: [emoticon, sniley, frown, frown-o]

  - css: meh
    code: 0xf11a
    uid: 2c5055a9c9723725f49f0593a08535af
    search: [emoticon, sniley, meh]

  - css: lifebuoy
    code: 0xf1cd
    uid: ebffa4e734c8379ffee4fbfe49264d94
    search: [lifebuoy, support]

  - css: soccer-ball
    code: 0xf1e3
    uid: cf62866c0cfe3dd14455b381c724f8e1
    search: [soccer, ball]

  - css: newspaper
    code: 0xf1ea
    uid: 032bd8bbd70adf90ead98b6813bfe446
    search: [newspaper]

  - css: copyright
    code: 0xf1f9
    uid: 4a74a0f87d4089efe7aba1825bff4193
    search: [copyright]

  - css: cc
    code: 0xf20a
    uid: 66faf6c4e3b0e4e33f06171e30253e26
    search: [cc]

  - css: blank
    code: 0xf0c8
    uid: 2c2ca8a96b31781c9c8056d05c0a8980
    search: [blank, square]

  - css: lemon
    code: 0x1f34b
    uid: 5e0191587645a9f5d514ed4b0a0e008a
    from: 0xf094

  - css: object-group
    code: 0xf247
    uid: 7aa8cc552d9d6d19815750fc339cf090
    search: []

  - css: object-ungroup
    code: 0xf248
    uid: d4edf8563d5cb3b5f654808aa4fe438a
    search: []

  - css: sticky-note
    code: 0xf249
    uid: c116c18983825a9b32a23a62fd18e1e6
    search: []

  - css: clone
    code: 0xf24d
    uid: 6846d155ad5bda456569df81f3057faa
    search: []

  - css: hourglass
    code: 0xf254
    uid: bc9b0a766409e4ddeb2e9745c3e8130c
    search: []

  - css: hand-grab-o
    code: 0xf255
    uid: c82f1ec71a2c9e5af8b00fe5fe27f57e
    search: [hand-rock-o]

  - css: hand-paper-o
    code: 0xf256
    uid: abf08be829659c02d1f9a711daefa8ce
    search: [hand-stop-o]

  - css: hand-scissors-o
    code: 0xf257
    uid: dd0acda8a6217fd10e94d4feadccd90f
    search: []

  - css: hand-lizard-o
    code: 0xf258
    uid: 0eb9a32706e05e4f9f2561aa1bfbb7e9
    search: []

  - css: hand-spock-o
    code: 0xf259
    uid: 7a8becfd21312643b7be5463583e7425
    search: []

  - css: hand-pointer-o
    code: 0xf25a
    uid: 18e30ad120ce4b15d7e5c797e4bf0ee8
    search: []

  - css: hand-peace-o
    code: 0xf25b
    uid: 31562b831ad0016b89ddf9693214041f
    search: []

  - css: registered
    code: 0xf25d
    uid: c3371cca5561d470f45ae0a9c485b7ec
    search: []

  - css: calendar-plus-o
    code: 0xf271
    uid: e7eecc3cc44f3f4cad6229b202588308
    search: []

  - css: calendar-minus-o
    code: 0xf272
    uid: e66ec405e2e1f3bec6546b4e776924d3
    search: []

  - css: calendar-times-o
    code: 0xf273
    uid: a027a2ce420dfd6b660212d5ac6a7cc9
    search: []

  - css: calendar-check-o
    code: 0xf274
    uid: 9de4ac1aec6b1cca1929e1407eecf3db
    search: []

  - css: map
    code: 0xf279
    uid: 79beb8c7fcd56e1985b70e9a120cbcbf
    search: []

  - css: commenting
    code: 0xf27a
    uid: 53c28626072159c49f33b71d67138ad9
    search: []

  - css: pause-circle
    code: 0xf28b
    uid: 9c0fabd22e5b65b3ef7ed847eb864bcb
    search: []

  - css: stop-circle
    code: 0xf28d
    uid: 3363990fa5a224d75ed1740e1ec50bb6
    search: []

  - css: handshake-o
    code: 0xF2B5
    uid: 9fecfcfe680a469caedeeb40641a479f
    search: []

  - css: envelope-open
    code: 0xF2B6
    uid: f89739d9df5c9e70ece9be9cdf66abb6
    search: []

  - css: address-book
    code: 0xF2B9
    uid: 15899c11210bc9f45fc15a507789f6be
    search: []

  - css: address-card
    code: 0xF2BB
    uid: 79d27b578931fd441a6dc885c9dd88a6
    search: [vcard]

  - css: user-circle
    code: 0xF2BD
    uid: 818981e2ad316f18ae61cfa805d41309
    search: []

  - css: id-badge
    code: 0xF2C1
    uid: b2cc036e1ba44934896c345436ac44d1
    search: []

  - css: id-card
    code: 0xF2C2
    uid: 37b41cdae5ec9dab40e0c5bfff8a0ec8
    search: [drivers-license]

  - css: window-maximize
    code: 0xF2D0
    uid: 07f0832c07f3d9713fffb06c8bffa027
    search: []

  - css: window-minimize
    code: 0xF2D1
    uid: 04f022b8bd044d4ccfffd3887ff72088
    search: []

  - css: window-restore
    code: 0xF2D2
    uid: d0e62145dbf40f30e47b3819b8b43a8f
    search: []

  - css: window-close
    code: 0xF2D3
    uid: 7394501fc0b17cb7bda99538f92e26d6
    search: [times-rectangle]

  - css: snowflake-o
    code: 0xF2DC
    uid: 56f2eac13d2b397ff4a54dc38f783b95
    search: []

  - css: "frown-open"
    code: 0xF57A
    uid: a69860719e8b41c77f3fc430fc28a7c2
    search: []
  - css: "grin-beam"
    code: 0xF582
    uid: 0a9dd1c0f7b9adb211e96bb84d584722
    search: []
  - css: grimace
    code: 0xF57F
    uid: 98d3e5e1517b2edb60aaacdbf7a66dc5
    search: []
  - css: "sad-tear"
    code: 0xF5B4
    uid: ff70e8ce43924fbe2241f2b9e7654be2
    search: []
  - css: "sad-cry"
    code: 0xF5B3
    uid: 3696572c19bffec3de0ddce0af10c267
    search: []
  - css: gem
    code: 0xF3A5
    uid: 6b8465e6457759b39221b21c2f2beb06
    search: []
  - css: "laugh-squint"
    code: 0xF59B
    uid: 754bb3920d5e7901d1a60a780f88ef41
    search: []
  - css: surprise
    code: 0xF5C2
    uid: cd5e4850fc88201727b27440fe6705b7
    search: []
  - css: laugh
    code: 0xF599
    uid: 9731d6300d31a82b7eec6a636617d8d0
    search: []
  - css: "grin-hearts"
    code: 0xF584
    uid: 8f93e60ecbf2e49ff9af78efdd5bb568
    search: []
  - css: tired
    code: 0xF5C8
    uid: 93ace84f0fd9535120e15156d2aba544
    search: []
  - css: "money-bill-alt"
    code: 0xF3D1
    uid: 19fbec925c94ed3234b3c60db7026109
    search: []
  - css: "grin-wink"
    code: 0xF58C
    uid: 56ae3b4d280d131ce5b6d6d335615106
    search: []
  - css: images
    code: 0xF302
    uid: 52c9f1d702e4218b1069c2e7b2c1c07e
    search: []
  - css: grin
    code: 0xF580
    uid: 4a1102afafb872ebb8658b1c08cbaeb7
    search: []
  - css: "meh-blank"
    code: 0xF5A4
    uid: 02809f3206f7cbc746a95f4ceecbd6ee
    search: []
  - css: "grin-tongue-wink"
    code: 0xF58B
    uid: 81355562f5534150ab6f5d16221b5948
    search: []
  - css: "meh-rolling-eyes"
    code: 0xF5A5
    uid: 93c30b5548376216724f2ab137866a5d
    search: []
  - css: "grin-alt"
    code: 0xF581
    uid: 55e136b1d4794a2dc5d84a66550bafb6
    search: []
  - css: "trash-alt"
    code: 0xF2ED
    uid: 9d60d247f8d3842276b03ad2870fb4e5
    search: []
  - css: "comment-dots"
    code: 0xF4AD
    uid: 38b4445da8af0fe73dd224784cfd9cc6
    search: []
  - css: "grin-tongue"
    code: 0xF589
    uid: 828cf41b91777c72166dd241ee1b9300
    search: []
  - css: "laugh-beam"
    code: 0xF59A
    uid: 868ad3c74ede26d057d1e54cc708a8ff
    search: []
  - css: "smile-wink"
    code: 0xF4DA
    uid: 399cce8f992bdffbfc0d882bfd79b481
    search: []
  - css: dizzy
    code: 0xF567
    uid: aab9bcc80ca5fa60096e744cc8696c28
    search: []
  - css: kiss
    code: 0xF596
    uid: 7c54822b80d12873203717d3eb0216b7
    search: []
  - css: angry
    code: 0xF556
    uid: 77694430e62ce85d1ad8cbb0b77ffbd7
    search: []
  - css: "grin-tongue-squint"
    code: 0xF58A
    uid: 31cce49f118e3de69c374faaa128673a
    search: []
  - css: "arrow-alt-circle-up"
    code: 0xF35B
    uid: c8770cefdf105cf1a055629cab6fa7ca
    search: []
  - css: clipboard
    code: 0xF328
    uid: a478d565aa82b05fa1961d4450932ad0
    search: []
  - css: "laugh-wink"
    code: 0xF59C
    uid: 47eea26b511763b89f9b41f5877908c4
    search: []
  - css: "grin-beam-sweat"
    code: 0xF583
    uid: f9ef2a243d10084f4abbfa0bfe70f19a
    search: []
  - css: "grin-tears"
    code: 0xF588
    uid: 98e2fd6c451ba2db8ccae8c848c5952e
    search: []
  - css: "arrow-alt-circle-left"
    code: 0xF359
    uid: 1e110ef875e028a79594da1f36f5bae0
    search: []
  - css: "arrow-alt-circle-down"
    code: 0xF358
    uid: 5c9ee70d79b01c51ce13881f4e91c36c
    search: []
  - css: "kiss-beam"
    code: 0xF597
    uid: b22597dbf0990d20a95d5571a4272557
    search: []
  - css: "grin-stars"
    code: 0xF587
    uid: 58f67ea35750a02d0ee2eab0caefb263
    search: []
  - css: "grin-squint"
    code: 0xF585
    uid: 69c3cbb26bf2aca20f8fd7beafbecc20
    search: []
  - css: "arrow-alt-circle-right"
    code: 0xF35A
    uid: 91c50025ef0b6d0255426ac8268e8e48
    search: []
  - css: "smile-beam"
    code: 0xF5B8
    uid: 688fbb401975b9a1cad94ef728fd8ed1
    search: []
  - css: flushed
    code: 0xF579
    uid: f212abd6681138f9d43d6921325a7797
    search: []
  - css: "kiss-wink-heart"
    code: 0xF598
    uid: 348509c3db91236c64aee428a8ae2446
    search: []
  - css: "window-close"
    code: 0xF410
    uid: 909d1dc87be5564e1d4b61f54efc36cc
    search: []
  - css: "grin-squint-tears"
    code: 0xF586
    uid: 9791dbe1ef42e1b5ee0f733c93aff3a2
    search: []
