---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%.
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Dave Gandy
  homepage: http://fortawesome.github.com/Font-Awesome/
  email: dave@davegandy.com
  twitter: https://twitter.com/fontawesome/
  github: https://github.com/FortAwesome/Font-Awesome
  license: SIL
  #license_url: http://creativecommons.org/licenses/by/3.0/

  css_prefix_text: "icon-"
  columns: 4

#transform:
#  baseline: 0.5
#  rescale: 1.053
#  # offset: -0.05


font:
  version: "5.2.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: fa5regular

  fullname: Font Awesome 5 Free - regular
  familyname: Font Awesome 5 Free

  copyright: Copyright (C) 2017 by Dave Gandy

  ascent: 850
  descent: 150
  weight: "Regular"


glyphs: 
  - css: "address-book-o"
    code: 0xF2B9
    uid: f0f24c5bf41e610fc3ccf4c0f8a30b14
    search: []
  - css: "address-card-o"
    code: 0xF2BB
    uid: 26e248aab76cc387ce5cabdf2d6a87c9
    search: [vcard]
  - css: angry
    code: 0xF556
    uid: 0f521dfd78b28ece3e93b5941ac3c78f
    search: []
  - css: "arrow-alt-circle-down"
    code: 0xF358
    uid: b7850ba2deeda60158caef158ebf3137
    search: []
  - css: "arrow-alt-circle-left"
    code: 0xF359
    uid: f8dfd0c2d4e581da18f9a51185a72cc2
    search: []
  - css: "arrow-alt-circle-right"
    code: 0xF35A
    uid: 3d0c6e2a0ce0820ab4fc45287cd9e866
    search: []
  - css: "arrow-alt-circle-up"
    code: 0xF35B
    uid: d0935856f894655f26cd43054e44555f
    search: []
  - css: "bell-slash"
    code: 0xF1F6
    uid: 1c8e05459740f03051dd99cd11a98a52
    search: []
  - css: bell
    code: 0xF0F3
    uid: 15ad40335dbbaef14136e39b8c52e9dc
    search: [alert, bell, jingle, bell-o]
  - css: "bookmark-empty"
    code: 0xF02E
    uid: 33d6475d63a955359157a9ac48c60725
    search: [bookmark]
  - css: building
    code: 0xF1AD
    uid: 6c8f8d748d1585d494f0ebe1411290a7
    search: [building]
  - css: "calendar-alt"
    code: 0xF073
    uid: 34027029cb32fa0be91504506b734899
    search: []
  - css: "calendar-check-o"
    code: 0xF274
    uid: e17e6508ea01265223be22548a6b17b9
    search: []
  - css: "calendar-minus-o"
    code: 0xF272
    uid: f7a6a49de5532669ca44a92e9408ff3c
    search: []
  - css: "calendar-plus-o"
    code: 0xF271
    uid: 2cfc61b8fb5938638bb94603c3fc39b0
    search: []
  - css: "calendar-times-o"
    code: 0xF273
    uid: b05e2591009de3bbc27e639672fe9ddd
    search: []
  - css: "calendar-empty"
    code: 0xF133
    uid: ba05353fd0bd1877fa28728cbdeedb17
    search: [calendar, date]
  - css: "caret-square-down"
    code: 0xF150
    uid: b5e55a15a064fda7b0f01f217e27e87f
    search: []
  - css: "caret-square-left"
    code: 0xF191
    uid: ff64552f3809ba0f236dacf1e0a2342b
    search: []
  - css: "caret-square-right"
    code: 0xF152
    uid: 98bf1bdcdd9f4d71cb299cd0ffd28058
    search: []
  - css: "caret-square-up"
    code: 0xF151
    uid: 49ab0d7183eb973dfa378c6133060860
    search: []
  - css: "chart-bar"
    code: 0xF080
    uid: 57825f51434dc684685bd3ac49c42bb7
    search: [chart, bar, diagram, bar-chart]
  - css: "check-circle"
    code: 0xF058
    uid: 84089c2371fdef791f1fdccc45a4df52
    search: []
  - css: "check-square"
    code: 0xF14A
    uid: de3d643a8877d97fb27911bf78dc7059
    search: []
  - css: "circle-empty"
    code: 0xF111
    uid: f540ddd8dae555dfdb5050421e8b1364
    search: [circle]
  - css: clipboard
    code: 0xF328
    uid: 6dff29274add66cd9e875700104ef213
    search: []
  - css: clock
    code: 0xF017
    uid: e40096c6445594f2afaa1235f99cfda5
    search: [clock, time, clock-o]
  - css: clone
    code: 0xF24D
    uid: 806d68c3f6469f53d314d4e6d73f6fc3
    search: []
  - css: "closed-captioning"
    code: 0xF20A
    uid: 9e11b77edee86823f734da85835b6905
    search: []
  - css: "comment-alt"
    code: 0xF27A
    uid: 0f0188b1cf3324d2f944118cf4c937dc
    search: []
  - css: "comment-dots"
    code: 0xF4AD
    uid: ddc5bcb3cd824cfff04b24f6857db504
    search: []
  - css: "comment-empty"
    code: 0xF075
    uid: 3ecdddfdd72d7a42041bcb85edec3912
    search: [comment, reply, write]
  - css: comments
    code: 0xF086
    uid: 49b5518b27c449259bc10608c3fd61df
    search: []
  - css: compass
    code: 0xF14E
    uid: f23f41ed668a3175f1233f5c21c3f428
    search: [compass]
  - css: copy
    code: 0xF0C5
    uid: 8ee82863a2abc738828389d54992d301
    search: []
  - css: copyright
    code: 0xF1F9
    uid: d8aab0ab416201da24d81d16bc7fdba9
    search: [copyright]
  - css: "credit-card"
    code: 0xF09D
    uid: aec8e746b7f279676137084a1987fad7
    search: [card, plastic, credit]
  - css: dizzy
    code: 0xF567
    uid: e7269e29489b03463e5eb40f962533a2
    search: []
  - css: "dot-circle"
    code: 0xF192
    uid: 39713c7e913244040989cff740daa6c8
    search: []
  - css: edit
    code: 0xF044
    uid: 7b443ceb2b4e0fdca3a176b753bf3a90
    search: [pencil, write, reply, edit]
  - css: "envelope-open-o"
    code: 0xF2B6
    uid: 4c3bfab9e74c9ce5ab5ef31253b0bbb8
    search: []
  - css: envelope
    code: 0xF0E0
    uid: 214b9d1daf07f5e1db72726bef44878c
    search: []
  - css: "eye-slash"
    code: 0xF070
    uid: 16a24d78c1c38a245c106774aecadba4
    search: []
  - css: eye
    code: 0xF06E
    uid: 9f3b508081908f93123940cac3a8ad75
    search: [eye, subscribe]
  - css: "file-alt"
    code: 0xF15C
    uid: 682a7625de11f4a53c40b63ab2eb41d0
    search: []
  - css: "file-archive"
    code: 0xF1C6
    uid: 67f937d5f232a6074e2d894794fd0ac3
    search: [file, archive, file-zip-o]
  - css: "file-audio"
    code: 0xF1C7
    uid: 26f99f74b896e4f731a2306735b396e4
    search: [file, audio, sound]
  - css: "file-code"
    code: 0xF1C9
    uid: b0b405b86b829a61d7706fb6342f041a
    search: [file, code]
  - css: "file-excel"
    code: 0xF1C3
    uid: 11df1366a47856a9050871ff252cb634
    search: [file, excel]
  - css: "file-image"
    code: 0xF1C5
    uid: b8e6ee3adc6ae9039e9eb411721e0537
    search: [file, image, picture]
  - css: "file-pdf"
    code: 0xF1C1
    uid: b4636ad27c0afd3a67f0ada3691a8980
    search: [file, pdf, file-pdf-o]
  - css: "file-powerpoint"
    code: 0xF1C4
    uid: 5b3a3a27bbe84daa06b898e7d00b99b1
    search: [file, powerpoint]
  - css: "file-video"
    code: 0xF1C8
    uid: 4c1212b689000cd5dfc3740044905eea
    search: [file, video, movie]
  - css: "file-word"
    code: 0xF1C2
    uid: 4634ce70e152c751496c6ecbe78ffcee
    search: [file, word]
  - css: file
    code: 0xF15B
    uid: 61672ad073539fb6cf3409a52ca5567b
    search: []
  - css: "flag-empty"
    code: 0xF024
    uid: f8ab512dc2bba43e94e23dc264c5539d
    search: [flag]
  - css: flushed
    code: 0xF579
    uid: 140bacfb5dcdf7fff426401e953ba3b8
    search: []
  - css: "folder-open-empty"
    code: 0xF07C
    uid: 3759e24bfbcff871be0c55c678420de5
    search: [folder]
  - css: "folder-empty"
    code: 0xF07B
    uid: e55c6cc61a5eb689c039032bc34f6853
    search: [folder]
  - css: "frown-open"
    code: 0xF57A
    uid: 9dd51e53448e306421e87d52be96f397
    search: []
  - css: frown
    code: 0xF119
    uid: 1433249033337050fc644d0284085a43
    search: [emoticon, sniley, frown, frown-o]
  - css: futbol
    code: 0xF1E3
    uid: 169ef6d1e894a94bf6a049d7b5d1098d
    search: []
  - css: gem
    code: 0xF3A5
    uid: 4e3e385d541d21ead20bdf91042bc1cf
    search: []
  - css: grimace
    code: 0xF57F
    uid: ffeaa123a479a25a8b8b9cc4f17cf4ef
    search: []
  - css: "grin-alt"
    code: 0xF581
    uid: 9cfad83466805a3ff88fff73a6f4ead7
    search: []
  - css: "grin-beam-sweat"
    code: 0xF583
    uid: 2a12d27e273677289dd2df04a5c0de98
    search: []
  - css: "grin-beam"
    code: 0xF582
    uid: d49816b054c4ecabbc20aaaee9fd1fdf
    search: []
  - css: "grin-hearts"
    code: 0xF584
    uid: 16d8faa943835863591d594673b31379
    search: []
  - css: "grin-squint-tears"
    code: 0xF586
    uid: dd833ca09daf6c7a8f760a4f9b87df83
    search: []
  - css: "grin-squint"
    code: 0xF585
    uid: d85d5ca58531266f21f1476fb5846f6f
    search: []
  - css: "grin-stars"
    code: 0xF587
    uid: 572608d75bde2e0874c58a286ab42c7d
    search: []
  - css: "grin-tears"
    code: 0xF588
    uid: e1a68f3ad5bfbdf9a2cc7a42efc24beb
    search: []
  - css: "grin-tongue-squint"
    code: 0xF58A
    uid: 38922cf064cf5f4edc8a6a266ee0681c
    search: []
  - css: "grin-tongue-wink"
    code: 0xF58B
    uid: ee4f31ddcd1b37587bdf64d513667cce
    search: []
  - css: "grin-tongue"
    code: 0xF589
    uid: c2f1adf2c8b777d74e9f6822a14f8b6d
    search: []
  - css: "grin-wink"
    code: 0xF58C
    uid: 032dba7704abfc6e498c6543a9ea5276
    search: []
  - css: grin
    code: 0xF580
    uid: 985dd626f463529a5759d3c62246f0b3
    search: []
  - css: "hand-lizard-o"
    code: 0xF258
    uid: 0912b46c5b48ea693a2cfedef1477ae4
    search: []
  - css: "hand-paper-o"
    code: 0xF256
    uid: a86e3659129876861939d94b9d839692
    search: []
  - css: "hand-peace-o"
    code: 0xF25B
    uid: 1f99d05530b16a89c545f0f326aad14c
    search: []
  - css: "hand-point-down"
    code: 0xF0A7
    uid: 823b690f1edcf449b569507da541a7a9
    search: []
  - css: "hand-point-left"
    code: 0xF0A5
    uid: 1c07aef08c363d7e6129649eda6db3cb
    search: []
  - css: "hand-point-right"
    code: 0xF0A4
    uid: 96a4c1bc17bd66a643fa512024deff78
    search: []
  - css: "hand-point-up"
    code: 0xF0A6
    uid: 57ffd0b597a1d586c10f8abfc9825a98
    search: []
  - css: "hand-pointer-o"
    code: 0xF25A
    uid: 49e0d07026114748ed11188e55c4789b
    search: []
  - css: "hand-rock"
    code: 0xF255
    uid: b84d785f8b67e7468fdcc3b7e19607cb
    search: []
  - css: "hand-scissors-o"
    code: 0xF257
    uid: c0a2070d8a797227b550ecab542d7318
    search: []
  - css: "hand-spock-o"
    code: 0xF259
    uid: 472a28f47d5736deb16fdb11615beeea
    search: []
  - css: "handshake-o"
    code: 0xF2B5
    uid: 83b3dc52d5139225334724dac9744b49
    search: []
  - css: hdd
    code: 0xF0A0
    uid: e6726908724faaad5776fde874f68830
    search: [hdd, drive, disk]
  - css: "heart-empty"
    code: 0xF004
    uid: 9c78974ffc6f1162743c7c4fd1542543
    search: [heart]
  - css: hospital
    code: 0xF0F8
    uid: 4676d44a6b4c9c4274ba81dddbfdf37e
    search: [hospital      ]
  - css: "hourglass-o"
    code: 0xF254
    uid: 31f599c0e61cef3f763dd1a8a6525ce4
    search: []
  - css: "id-badge"
    code: 0xF2C1
    uid: fd1d0b32c310374eb05387786ad0b529
    search: []
  - css: "id-card-o"
    code: 0xF2C2
    uid: ae7c02d262a774cd31f0995fdac2af7e
    search: [drivers-license]
  - css: image
    code: 0xF03E
    uid: 8f88aeb44e5f08d61a2c3cdb0dc63c42
    search: []
  - css: images
    code: 0xF302
    uid: 25d32a3c4b087b049463ce67d7f97275
    search: []
  - css: keyboard
    code: 0xF11C
    uid: d40a47d03b0298742988f9a5656004e0
    search: [keyboard, keyboard-o]
  - css: "kiss-beam"
    code: 0xF597
    uid: 937bee88e47dd9b6a5d3747d23df32c7
    search: []
  - css: "kiss-wink-heart"
    code: 0xF598
    uid: 20a4fbe6c429bad3e75ca965f06867e7
    search: []
  - css: kiss
    code: 0xF596
    uid: 9263e1ae3192940f41bb9618f4639cf0
    search: []
  - css: "laugh-beam"
    code: 0xF59A
    uid: 070ed8779be17f85d527d4a2cf386281
    search: []
  - css: "laugh-squint"
    code: 0xF59B
    uid: 05e61d328768cb801bcc936b21e651fd
    search: []
  - css: "laugh-wink"
    code: 0xF59C
    uid: e8e03b31bf3c9ba44b2f74cded9dbcd9
    search: []
  - css: laugh
    code: 0xF599
    uid: 4d41402947290524921e00cf86d3bd4d
    search: []
  - css: lemon
    code: 0xF094
    uid: f9f328a3b1f9743e1779048b739df482
    search: []
  - css: "life-ring"
    code: 0xF1CD
    uid: 269993e4531af20a7caedd38c8fd9ee1
    search: []
  - css: lightbulb
    code: 0xF0EB
    uid: a5ff7cdcd26bb7660758b3cf4bd6818f
    search: [idea, lamp, light, lightbulb-o]
  - css: "list-alt"
    code: 0xF022
    uid: 0618cf47321821b7210b787edc2ec76d
    search: [list]
  - css: "map-o"
    code: 0xF279
    uid: 750182e0a074a71027e4f0866a8bfa2f
    search: []
  - css: "meh-blank"
    code: 0xF5A4
    uid: d7332fee708e0d37954cd476937d1226
    search: []
  - css: "meh-rolling-eyes"
    code: 0xF5A5
    uid: 94756a09f053e05f49e8a959c013ba31
    search: []
  - css: meh
    code: 0xF11A
    uid: 279b8dadc99013b4da1a50ef53cc0881
    search: [emoticon, sniley, meh]
  - css: "minus-square"
    code: 0xF146
    uid: b165c39968db539f8a80d077902faf4d
    search: []
  - css: "money-bill-alt"
    code: 0xF3D1
    uid: 7433677fde3e7a69a4981e60c149455b
    search: []
  - css: moon
    code: 0xF186
    uid: 0ee4d9a93c42a171ea925cf9e75f2df5
    search: [moon]
  - css: newspaper
    code: 0xF1EA
    uid: 24f1dfe4243912aef3810a3f017b7f23
    search: [newspaper]
  - css: "object-group"
    code: 0xF247
    uid: a00661888237ffa91d59a7fb479d8c52
    search: []
  - css: "object-ungroup"
    code: 0xF248
    uid: ce478d7dc7c27cec4f38e4a94135e461
    search: []
  - css: "paper-plane-empty"
    code: 0xF1D8
    uid: 91c63a2aee3c2bf1bc55170d140876e3
    search: [flight, plane, airplane, fly]
  - css: "pause-circle-o"
    code: 0xF28B
    uid: 1a9c9192b44f9c59ac06ecd306e7c7cf
    search: []
  - css: "play-circle"
    code: 0xF144
    uid: 019b5c49c576467bc2ff160eddf889eb
    search: []
  - css: "plus-square"
    code: 0xF0FE
    uid: d1d03ff4860adbb56c6d2db3a978c70e
    search: []
  - css: "question-circle-o"
    code: 0xF059
    uid: 6eed3527e6d5fefc108fa8b9dee0b143
    search: []
  - css: registered
    code: 0xF25D
    uid: d7c2c505cfbb7c225778889cce7ddb90
    search: []
  - css: "sad-cry"
    code: 0xF5B3
    uid: 50a2a23f1eee80948c187759a3b73577
    search: []
  - css: "sad-tear"
    code: 0xF5B4
    uid: 666b5b90b2705da52dfcaa6b8dfc0ecb
    search: []
  - css: save
    code: 0xF0C7
    uid: ecdde0ce2eb34c42b0930c4c4336346f
    search: []
  - css: "share-square"
    code: 0xF14D
    uid: ce80a2ae0e745934ed58221180e565a3
    search: []
  - css: "smile-beam"
    code: 0xF5B8
    uid: 193178f966a206bd42a1f5f3a7948230
    search: []
  - css: "smile-wink"
    code: 0xF4DA
    uid: 54a34f2881b81b008300707ed396cb5d
    search: []
  - css: smile
    code: 0xF118
    uid: 10248ed9813bad1f5bdb9b96ed1b8643
    search: [emoticon, sniley, smile, happy, smile-o]
  - css: "snowflake-o"
    code: 0xF2DC
    uid: 049f00347df71824fbb825c57b89620b
    search: []
  - css: square
    code: 0xF0C8
    uid: c4ccb0ad15067bdeacdfc42d18cd34ab
    search: []
  - css: "star-half"
    code: 0xF089
    uid: 8776ff55f936dff8c5e84d0a6b44b95f
    search: [star]
  - css: "star-empty"
    code: 0xF005
    uid: 45fc2ca7e5f5fec6401a476298a75137
    search: [star]
  - css: "sticky-note-o"
    code: 0xF249
    uid: 0e4d0b72daed5b4d02feb94c72fd46c6
    search: []
  - css: "stop-circle-o"
    code: 0xF28D
    uid: 7052d7cc710c9e1b4378fb23e900c586
    search: []
  - css: sun
    code: 0xF185
    uid: bc094948b1be47903a5a1a93570db027
    search: [sun, sun-o]
  - css: surprise
    code: 0xF5C2
    uid: f5dad95b84db3f81959b46b5fadb3a35
    search: []
  - css: "thumbs-down"
    code: 0xF165
    uid: 8776575538614a2f207cc7f797d06d1d
    search: [thumbs, vote, down, unlike, dislike, thumbs-o-down]
  - css: "thumbs-up"
    code: 0xF164
    uid: 534d04069f9f3bcd2e2e012e18e2c988
    search: [thumbs, vote, up, like, love, thumbs-o-up]
  - css: "times-circle"
    code: 0xF057
    uid: 3999d4c8fdcb652f138c2f1690cc2cfc
    search: []
  - css: tired
    code: 0xF5C8
    uid: bd8948e801877a9e60e0f801bc7799c7
    search: []
  - css: "trash-alt"
    code: 0xF2ED
    uid: 255066d7cb7f508479477ae12f79ee92
    search: []
  - css: "user-circle-o"
    code: 0xF2BD
    uid: b76a498fd8e17db683d4d24177b8a3ef
    search: []
  - css: "user-o"
    code: 0xF007
    uid: d0b7205c56c55798e8e2d0931aee7518
    search: [profile, contact, user]
  - css: "window-close-o"
    code: 0xF410
    uid: 38f12a427929894c953bf3770e90d796
    search: [times-rectangle]
  - css: "window-maximize"
    code: 0xF2D0
    uid: b5d443713b85189fe4110789845c0514
    search: []
  - css: "window-minimize"
    code: 0xF2D1
    uid: 78e43d6a1117ba36192c8b0118b8e7a6
    search: []
  - css: "window-restore"
    code: 0xF2D2
    uid: 0f2455209d614a76d53409e3d7169725
    search: []
