---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%.
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: Dave Gandy
  homepage: http://fortawesome.github.com/Font-Awesome/
  email: dave@davegandy.com
  twitter: https://twitter.com/fontawesome/
  github: https://github.com/FortAwesome/Font-Awesome
  license: SIL
  #license_url: http://creativecommons.org/licenses/by/3.0/

  css_prefix_text: "icon-"
  columns: 4

#transform:
#  baseline: 0.5
#  rescale: 1.053
#  # offset: -0.05


font:
  version: "5.2.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: fa5regular

  fullname: Font Awesome 5 Free - regular
  familyname: Font Awesome 5 Free

  copyright: Copyright (C) 2017 by Dave Gandy

  ascent: 850
  descent: 150
  weight: "Regular"


glyphs:

  - css: "frown-open"
    code: 0xF57A
    uid: a69860719e8b41c77f3fc430fc28a7c2
    search: []
  - css: "grin-beam"
    code: 0xF582
    uid: 0a9dd1c0f7b9adb211e96bb84d584722
    search: []
  - css: grimace
    code: 0xF57F
    uid: 98d3e5e1517b2edb60aaacdbf7a66dc5
    search: []
  - css: "sad-tear"
    code: 0xF5B4
    uid: ff70e8ce43924fbe2241f2b9e7654be2
    search: []
  - css: "sad-cry"
    code: 0xF5B3
    uid: 3696572c19bffec3de0ddce0af10c267
    search: []
  - css: gem
    code: 0xF3A5
    uid: 6b8465e6457759b39221b21c2f2beb06
    search: []
  - css: "laugh-squint"
    code: 0xF59B
    uid: 754bb3920d5e7901d1a60a780f88ef41
    search: []
  - css: surprise
    code: 0xF5C2
    uid: cd5e4850fc88201727b27440fe6705b7
    search: []
  - css: laugh
    code: 0xF599
    uid: 9731d6300d31a82b7eec6a636617d8d0
    search: []
  - css: "grin-hearts"
    code: 0xF584
    uid: 8f93e60ecbf2e49ff9af78efdd5bb568
    search: []
  - css: tired
    code: 0xF5C8
    uid: 93ace84f0fd9535120e15156d2aba544
    search: []
  - css: "money-bill-alt"
    code: 0xF3D1
    uid: 19fbec925c94ed3234b3c60db7026109
    search: []
  - css: "grin-wink"
    code: 0xF58C
    uid: 56ae3b4d280d131ce5b6d6d335615106
    search: []
  - css: images
    code: 0xF302
    uid: 52c9f1d702e4218b1069c2e7b2c1c07e
    search: []
  - css: grin
    code: 0xF580
    uid: 4a1102afafb872ebb8658b1c08cbaeb7
    search: []
  - css: "meh-blank"
    code: 0xF5A4
    uid: 02809f3206f7cbc746a95f4ceecbd6ee
    search: []
  - css: "grin-tongue-wink"
    code: 0xF58B
    uid: 81355562f5534150ab6f5d16221b5948
    search: []
  - css: "meh-rolling-eyes"
    code: 0xF5A5
    uid: 93c30b5548376216724f2ab137866a5d
    search: []
  - css: "grin-alt"
    code: 0xF581
    uid: 55e136b1d4794a2dc5d84a66550bafb6
    search: []
  - css: "trash-alt"
    code: 0xF2ED
    uid: 9d60d247f8d3842276b03ad2870fb4e5
    search: []
  - css: "comment-dots"
    code: 0xF4AD
    uid: 38b4445da8af0fe73dd224784cfd9cc6
    search: []
  - css: "grin-tongue"
    code: 0xF589
    uid: 828cf41b91777c72166dd241ee1b9300
    search: []
  - css: "laugh-beam"
    code: 0xF59A
    uid: 868ad3c74ede26d057d1e54cc708a8ff
    search: []
  - css: "smile-wink"
    code: 0xF4DA
    uid: 399cce8f992bdffbfc0d882bfd79b481
    search: []
  - css: dizzy
    code: 0xF567
    uid: aab9bcc80ca5fa60096e744cc8696c28
    search: []
  - css: kiss
    code: 0xF596
    uid: 7c54822b80d12873203717d3eb0216b7
    search: []
  - css: angry
    code: 0xF556
    uid: 77694430e62ce85d1ad8cbb0b77ffbd7
    search: []
  - css: "grin-tongue-squint"
    code: 0xF58A
    uid: 31cce49f118e3de69c374faaa128673a
    search: []
  - css: "arrow-alt-circle-up"
    code: 0xF35B
    uid: c8770cefdf105cf1a055629cab6fa7ca
    search: []
  - css: clipboard
    code: 0xF328
    uid: a478d565aa82b05fa1961d4450932ad0
    search: []
  - css: "laugh-wink"
    code: 0xF59C
    uid: 47eea26b511763b89f9b41f5877908c4
    search: []
  - css: "grin-beam-sweat"
    code: 0xF583
    uid: f9ef2a243d10084f4abbfa0bfe70f19a
    search: []
  - css: "grin-tears"
    code: 0xF588
    uid: 98e2fd6c451ba2db8ccae8c848c5952e
    search: []
  - css: "arrow-alt-circle-left"
    code: 0xF359
    uid: 1e110ef875e028a79594da1f36f5bae0
    search: []
  - css: "arrow-alt-circle-down"
    code: 0xF358
    uid: 5c9ee70d79b01c51ce13881f4e91c36c
    search: []
  - css: "kiss-beam"
    code: 0xF597
    uid: b22597dbf0990d20a95d5571a4272557
    search: []
  - css: "grin-stars"
    code: 0xF587
    uid: 58f67ea35750a02d0ee2eab0caefb263
    search: []
  - css: "grin-squint"
    code: 0xF585
    uid: 69c3cbb26bf2aca20f8fd7beafbecc20
    search: []
  - css: "arrow-alt-circle-right"
    code: 0xF35A
    uid: 91c50025ef0b6d0255426ac8268e8e48
    search: []
  - css: "smile-beam"
    code: 0xF5B8
    uid: 688fbb401975b9a1cad94ef728fd8ed1
    search: []
  - css: flushed
    code: 0xF579
    uid: f212abd6681138f9d43d6921325a7797
    search: []
  - css: "kiss-wink-heart"
    code: 0xF598
    uid: 348509c3db91236c64aee428a8ae2446
    search: []
  - css: "window-close"
    code: 0xF410
    uid: 909d1dc87be5564e1d4b61f54efc36cc
    search: []
  - css: "grin-squint-tears"
    code: 0xF586
    uid: 9791dbe1ef42e1b5ee0f733c93aff3a2
    search: []
  - css: smile
    code: 0xF118
    uid: 5079d307abd67f24deb4f6d61ae9f363
    search: []
  - css: "hand-scissors"
    code: 0xF257
    uid: 19c259812c8454924ca3f92f21f563ae
    search: []
  - css: "file-audio"
    code: 0xF1C7
    uid: 0b1e8bffbb60d604a3faa166527bd642
    search: []
  - css: clone
    code: 0xF24D
    uid: 557221cbdb574aaedf88a56fa40ea76c
    search: []
  - css: "credit-card"
    code: 0xF09D
    uid: f7cc43477b8061468948dfa5406abe88
    search: []
  - css: heart
    code: 0xF004
    uid: c89a43c4eb9357cd518318360578bf7a
    search: []
  - css: "calendar-minus"
    code: 0xF272
    uid: 9fe9bf2258e09388c2b41fd8b35be1ab
    search: []
  - css: "object-group"
    code: 0xF247
    uid: 426eaa460788e89e3c25a1d891d55f14
    search: []
  - css: "plus-square"
    code: 0xF0FE
    uid: 2f4a538b3b7a9ff353d5e113bcc502ce
    search: []
  - css: "file-powerpoint"
    code: 0xF1C4
    uid: 6c106ccf486068e1025487dcb5e03840
    search: []
  - css: "times-circle"
    code: 0xF057
    uid: 33dae1b4adf2321881401418a76eab20
    search: []
  - css: "file-video"
    code: 0xF1C8
    uid: 5f1d80c6fc5902da4f843cd0ee80af4a
    search: []
  - css: "id-card"
    code: 0xF2C2
    uid: af8188ba349a2a69948b4d1724f1e565
    search: []
  - css: "hand-paper"
    code: 0xF256
    uid: e55fcc75d483a241eadf7ccd846ac851
    search: []
  - css: "dot-circle"
    code: 0xF192
    uid: 7fba25ab48e35c27b3b395ac77ab43de
    search: []
  - css: compass
    code: 0xF14E
    uid: 9661b1c926f17bf3598375ff3df821e2
    search: []
  - css: save
    code: 0xF0C7
    uid: 77c30467201643de4a682ad744974572
    search: []
  - css: "file-image"
    code: 0xF1C5
    uid: aea59852307b6c88d29b1f1daabaceb0
    search: []
  - css: "calendar-plus"
    code: 0xF271
    uid: 668bc9c4eebaeea9bc594a848b713006
    search: []
  - css: bookmark
    code: 0xF02E
    uid: 9e4ea92b5a588b24e33a1a56be3dcb3e
    search: []
  - css: building
    code: 0xF1AD
    uid: b584d77acb5c644cbf57a40ed55b2962
    search: []
  - css: "list-alt"
    code: 0xF022
    uid: b27b849de40d53c1fbee203ec5bb6b7f
    search: []
  - css: "id-badge"
    code: 0xF2C1
    uid: d3eab03d14f149a142a455262653034b
    search: []
  - css: folder
    code: 0xF07B
    uid: e2d171a16826e2f203985944a436f42a
    search: []
  - css: "thumbs-up"
    code: 0xF164
    uid: 96e852e0e602157ef5be319b554958e1
    search: []
  - css: "caret-square-down"
    code: 0xF150
    uid: fb128de3835caa21749e8f8326d42e5e
    search: []
  - css: lightbulb
    code: 0xF0EB
    uid: fbba0b6880e02dc1af40e7cc42cc5f07
    search: []
  - css: "question-circle"
    code: 0xF059
    uid: 1ce96caace938a2be56e1743ecc4d4d2
    search: []
  - css: hospital
    code: 0xF0F8
    uid: 3110d086cf5ee34bcb90e4bf031a15eb
    search: []
  - css: "star-half"
    code: 0xF089
    uid: 183a17e55456190f77178526b3073c41
    search: []
  - css: "file-pdf"
    code: 0xF1C1
    uid: d5cd898fd351bd986d0e7d57ac2bacac
    search: []
  - css: "pause-circle"
    code: 0xF28B
    uid: 0e95d053fab49ac59ae8f10b4a8e0485
    search: []
  - css: "file-word"
    code: 0xF1C2
    uid: ba83a692b51ac6cc959cb51f295331a8
    search: []
  - css: bell
    code: 0xF0F3
    uid: ee9c06391a43fd5a85ebeab9741bd4a7
    search: []
  - css: snowflake
    code: 0xF2DC
    uid: 0b4534ad9f17b48f18ae5828d9588a43
    search: []
  - css: "file-code"
    code: 0xF1C9
    uid: cfd38c2fe0ae890eb305a7c83b35a0b2
    search: []
  - css: comment
    code: 0xF075
    uid: 8199d78ff41500132eaa364d2dbaeb0e
    search: []
  - css: hourglass
    code: 0xF254
    uid: b51e5eedd893493757a2ce35446df1a9
    search: []
  - css: star
    code: 0xF005
    uid: 1f72004f049c169b7f3a0238cf1cfd23
    search: []
  - css: futbol
    code: 0xF1E3
    uid: c1b1c3277c1c511db54a890e0c3d6b38
    search: []
  - css: "sticky-note"
    code: 0xF249
    uid: cb0a6fafd5e95a7bcfab8602be16f5bc
    search: []
  - css: "chart-bar"
    code: 0xF080
    uid: 4b3c7d9f338cd4b195b0db24accbb1e2
    search: []
  - css: "stop-circle"
    code: 0xF28D
    uid: 2124a0d43099f9330a395a9265581aa8
    search: []
  - css: "calendar-alt"
    code: 0xF073
    uid: 2896f02c6135b1092bef0ff6efb061b3
    search: []
  - css: "caret-square-up"
    code: 0xF151
    uid: fd877535c2e0fda3a3ce2950a4f6ce6d
    search: []
  - css: "hand-lizard"
    code: 0xF258
    uid: f207913b48bd674fb5a12cb6cffffaf0
    search: []
  - css: "hand-pointer"
    code: 0xF25A
    uid: b28bed46ee67ed18da40167bd54d3c0c
    search: []
  - css: "share-square"
    code: 0xF14D
    uid: e982a54eb1e222f490e53b40b8eae5ac
    search: []
  - css: meh
    code: 0xF11A
    uid: 6db5c52c85b0da465c9bba7ae22b55d6
    search: []
  - css: "hand-rock"
    code: 0xF255
    uid: 902bb4352ea627ad2cd8b898b7cda481
    search: []
  - css: "minus-square"
    code: 0xF146
    uid: f50bf8101d673d5d0df8515d49631e0c
    search: []
  - css: map
    code: 0xF279
    uid: a61dba6e767fb6d7e6ee9770d838c432
    search: []
  - css: "address-card"
    code: 0xF2BB
    uid: 686f9cf3ce87d25930bce0d99340f7fc
    search: []
  - css: "paper-plane"
    code: 0xF1D8
    uid: e043f1e945a53e50d62628a4b1ef592d
    search: []
  - css: envelope
    code: 0xF0E0
    uid: 749476b2a15fad2675a4a10f8cfe4a88
    search: []
  - css: "caret-square-right"
    code: 0xF152
    uid: 7b98bace27e85e6f5c4f6d14ca53787d
    search: []
  - css: "file-excel"
    code: 0xF1C3
    uid: 5d162c745f34c95988a6d9bff7420ee9
    search: []
  - css: sun
    code: 0xF185
    uid: 3573b38dd0a0163489435f6a7751e6ce
    search: []
  - css: "comment-alt"
    code: 0xF27A
    uid: e774c45f88d9b0233dd0d9b85d07d1c0
    search: []
  - css: image
    code: 0xF03E
    uid: dacd009d22c1786ffa252b279c331a57
    search: []
  - css: "object-ungroup"
    code: 0xF248
    uid: 95411b0dfb8f5e6267c4f9bbe0c9fe34
    search: []
  - css: "folder-open"
    code: 0xF07C
    uid: 7509d3432e97b574ac283f896520fe78
    search: []
  - css: "hand-point-right"
    code: 0xF0A4
    uid: df88aba7719b5be19b4694008a482be6
    search: []
  - css: "file-alt"
    code: 0xF15C
    uid: d79f86f6ce1ddf0292fda02d19330539
    search: []
  - css: square
    code: 0xF0C8
    uid: 2f06989cd180a8092b77f080ed292e8e
    search: []
  - css: "hand-point-down"
    code: 0xF0A7
    uid: 6f3190fcb7782bb88abe437c0c85fe7d
    search: []
  - css: frown
    code: 0xF119
    uid: 00e358da9d38dd832bb3542745f9acbf
    search: []
  - css: "bell-slash"
    code: 0xF1F6
    uid: 4d3437b179fc47c7c49e62d590aa5cc0
    search: []
  - css: "hand-point-up"
    code: 0xF0A6
    uid: b4df9b419c3f0d43b662276def7c269b
    search: []
  - css: newspaper
    code: 0xF1EA
    uid: 86b952d9afc258b92c4e6bc968151eca
    search: []
  - css: eye
    code: 0xF06E
    uid: 4725b2d3a53769b2ec0f6e61b92c2958
    search: []
  - css: "address-book"
    code: 0xF2B9
    uid: b50b55a0251fac94070275717c8bb59c
    search: []
  - css: "hand-peace"
    code: 0xF25B
    uid: 56af3d041e3e3b20c6a92988a9bfc58f
    search: []
  - css: moon
    code: 0xF186
    uid: 3c3f684e5e52ffd440a8e84175477bac
    search: []
  - css: "window-minimize"
    code: 0xF2D1
    uid: 67c7ff0558eaa8b7762c065a2fce52f0
    search: []
  - css: clock
    code: 0xF017
    uid: fc5a566026ebdcef91454fa10f40ddc4
    search: []
  - css: flag
    code: 0xF024
    uid: c82e89afceaddcf4354cfe6a26c84413
    search: []
  - css: "hand-spock"
    code: 0xF259
    uid: e39e8ce15677cc6702b3edc9d1f74b94
    search: []
  - css: comments
    code: 0xF086
    uid: 1a90bfa671f4834f24421bc79804353d
    search: []
  - css: copy
    code: 0xF0C5
    uid: f6ecbb261fe95a2310da5b9dc16e4a0b
    search: []
  - css: file
    code: 0xF15B
    uid: 3917d3148343b538d2da321ae505eeda
    search: []
  - css: calendar
    code: 0xF133
    uid: effdcca8e3445b426dd5aed9d294a7eb
    search: []
  - css: user
    code: 0xF007
    uid: c7d8eafd02cb68974db64c6b4dbd0e40
    search: []
  - css: "play-circle"
    code: 0xF144
    uid: a303bbc859ea164ccbbd00505be1f2d2
    search: []
  - css: "hand-point-left"
    code: 0xF0A5
    uid: aa0ce3f244d6142293d4fcf5b93fd8b3
    search: []
  - css: "closed-captioning"
    code: 0xF20A
    uid: 8876cf58a8c96942dd348552ddc0b35f
    search: []
  - css: "life-ring"
    code: 0xF1CD
    uid: d68e96b0fb4dec908d0289499c46c2e5
    search: []
  - css: "envelope-open"
    code: 0xF2B6
    uid: 0227c133cb371b7d52e80599dc6be4bc
    search: []
  - css: handshake
    code: 0xF2B5
    uid: 975512c2d2e642fa7ffe510a54abd283
    search: []
  - css: keyboard
    code: 0xF11C
    uid: 11d821631544995eba4720fbc4733d93
    search: []
  - css: circle
    code: 0xF111
    uid: 18b17401517ba1460c09f82d798bd10e
    search: []
  - css: "eye-slash"
    code: 0xF070
    uid: cba9e2e777015f5731b9715621b3fe1d
    search: []
  - css: "calendar-check"
    code: 0xF274
    uid: 0bfcff7dabca8b6cb9473651438117ca
    search: []
  - css: "check-square"
    code: 0xF14A
    uid: b27350c940c7e0ae463a603f266f25b9
    search: []
  - css: "thumbs-down"
    code: 0xF165
    uid: 23696cb870658aa11bb64dddaec1770d
    search: []
  - css: registered
    code: 0xF25D
    uid: f7000044bfe8ccdc9c966308f481624d
    search: []
  - css: lemon
    code: 0xF094
    uid: 47594d8a9d3965672094a1cc1450eac0
    search: []
  - css: "user-circle"
    code: 0xF2BD
    uid: a357f45198ff6f6f0a3ec9ff7d1cf927
    search: []
  - css: "file-archive"
    code: 0xF1C6
    uid: 5431c7e7e3d8180f42f6e5ff850a9d9e
    search: []
  - css: "check-circle"
    code: 0xF058
    uid: 1375ef408e9c66c7e8adf2d08c61a04a
    search: []
  - css: edit
    code: 0xF044
    uid: d279c5cce15e6a4f053059fb4f01cb12
    search: []
  - css: "window-restore"
    code: 0xF2D2
    uid: df37e231daf8fb56b82eb9b1ab83eb73
    search: []
  - css: hdd
    code: 0xF0A0
    uid: 25e702bfb27b395105310b9d87ecbafd
    search: []
  - css: "window-maximize"
    code: 0xF2D0
    uid: 972f0fa9c7745a104654d2ddb3085509
    search: []
  - css: "caret-square-left"
    code: 0xF191
    uid: 22e6d9acc27a08750451a09b6d9ea748
    search: []
  - css: copyright
    code: 0xF1F9
    uid: 46e6ebc04a61552c570faafe2a28abab
    search: []
  - css: "calendar-times"
    code: 0xF273
    uid: da6848a82bbec4b56be27bff9c08628c
    search: []
